### ISSUE TITLE
Styled but Unclickable Checkboxes

### ISSUE THREAD

**Issue by mgarf** [Semantic-Org/UI-Checkbox#1]
I have been trying to get this radio/checkboxes to work and I got styling to show but can't click/toggle any of them. I looked at the documentation but it's pretty sparse. Is there any initializers I need to add to the JS?

**Comment by ghost** [comment]
Hey @mgarf got the same issue here.. what did you do to resolve this situation?

**Comment by mgarf** [comment]
Hi @phildaponte ,

I used the top answer here for reference http://stackoverflow.com/questions/25846115/icheck-js-in-meteor-0-9-1-1. In terms of File placement and used this to initialize the code: 

  Template.[The name of your template].rendered = function() {
    this.$("input").iCheck({
      checkboxClass: "icheckbox_square-purple",
      radioClass: "iradio_square-purple"
    });
  };

**Comment by jlukic** [comment]
Oh no a competitor!

Checkboxes just need 

``` JavaScript
$('.ui.checkbox').checkbox();
```

Or match the iD field of the label to the input and don't use JavaScript.

See usage tab of checkbox docs

**Comment by mgarf** [comment]
sorry, I thought this was a issue regarding iCheck, didn't realize this was not the right repository. I wrote that response above when I was half asleep
